version: "3.8"

services:
  web1:
    image: webdevdockerimage:latest
    ports:
      - "3000:8080"
    deploy:
      replicas: 3

  web2:
    image: webdevdockerimage:latest
    ports:
      - "3001:8080"
    deploy:
      replicas: 2